"""add_ticket_delivery_status

Revision ID: 4f340a4d4589
Revises: 341aefbd6e29
Create Date: 2026-07-15 23:28:55.779201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f340a4d4589'
down_revision: Union[str, None] = '0002_quickwins'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('email_delivery_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('tickets', sa.Column('whatsapp_delivery_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('tickets', sa.Column('delivery_error_log', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'delivery_error_log')
    op.drop_column('tickets', 'whatsapp_delivery_status')
    op.drop_column('tickets', 'email_delivery_status')
    # ### end Alembic commands ###
